version: '3.8'

services:
  api:
    build: .
    container_name: verdance_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/verdance_db
      - DEBUG=False
      - ENVIRONMENT=production
    depends_on:
      - db
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
  
  db:
    image: postgres:14
    container_name: verdance_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=verdance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:alpine
    container_name: verdance_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: 